### ISSUE TITLE
[bug] crc delete from tray menu throws unhandled expection

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#117]
Tested on pre release bits for version `1.30.0` a regression failure was found

After start the cluster from the tray when trying to delete with the tray delete button it will show an unhandled exception:

![crc-1 30 0-delete-unhabdle](https://user-images.githubusercontent.com/1957899/127132940-18e0f899-1aa0-46c1-b858-cb0cbdd82d58.png)

Full error stack:

```bash
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CRCTray.CRCTray.DeleteReceived(DeleteResult result)
   at CRCTray.Helpers.DeleteReceivedHandler.Invoke(DeleteResult result)
   at CRCTray.Helpers.TaskHandlers.Delete()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRCTray.Helpers.TaskHelpers.<TryTaskAndNotify>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRCTray.CRCTray.<DeleteMenu_Click>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
crc-tray
    Assembly Version: 0.9.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Text.Json
    Assembly Version: 5.0.0.1
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
HttpOverStream.NamedPipe
    Assembly Version: 1.0.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
HttpOverStream
    Assembly Version: 1.0.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
HttpOverStream.Client
    Assembly Version: 1.0.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 5.0.0.1
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 0.9.0.0
    CodeBase: file:///C:/Program%20Files/CodeReady%20Containers/crc-tray.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by gbraad** [comment]
```
   at CRCTray.CRCTray.DeleteReceived(DeleteResult result)
   at CRCTray.Helpers.DeleteReceivedHandler.Invoke(DeleteResult result)
```

https://github.com/code-ready/tray-windows/blob/b43587eaaf3b5ce1e47d90359d92c1964a837f6f/Helpers/Handlers.cs#L65-L73

That is weird, as there is a null-check ... need more info to understand this.
